plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.4'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.fbisquerra'
version = '0.0.1-SNAPSHOT'
description = 'aboutme'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(26)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.register('installFrontend', Exec) {
    workingDir 'frontend'
    commandLine 'npm', 'install'
}

tasks.register('buildFrontend', Exec) {
    dependsOn 'installFrontend'
    workingDir 'frontend'
    commandLine 'npm', 'run', 'build'
}

tasks.named('build') {
    dependsOn 'buildFrontend'
}

tasks.register('dockerRun', Exec) {
    def profile = project.findProperty('profile') ?: 'local'
    def composeFile = profile == 'pro'
        ? 'infrastructure/docker/docker-compose.prod.yml'
        : 'infrastructure/docker/docker-compose.yml'

    dependsOn 'build'

    def args = ['docker', 'compose', '-f', composeFile, '--env-file', '.env', 'up', '--build', '-d']

    environment('SPRING_PROFILES_ACTIVE', profile)

    doFirst {
        println "Starting with profile: ${profile}"
        println "Running: ${args.join(' ')}"
    }

    commandLine args
}
