spring:
  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/aboutme}
    username: ${DB_USERNAME:aboutme}
    password: ${DB_PASSWORD:aboutme}
  jpa:
    show-sql: true

logging:
  level:
    com.fbisquerra: DEBUG
