spring:
  application:
    name: aboutme
  datasource:
    url: ${DB_URL:jdbc:mariadb://db:3306/aboutme}
    username: ${DB_USERNAME:aboutme}
    password: ${DB_PASSWORD:aboutme}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  flyway:
    enabled: true
  mail:
    host: smtp.resend.com
    port: 587
    username: resend
    password: ${RESEND_API_KEY}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8080

app:
  contact:
    recipient-email: francesc.bisquerra@gmail.com
    from-email: noreply@franbisquerra.dev
