name: aboutme

services:
  backend:
    build:
      context: ../..
      dockerfile: infrastructure/docker/backend/Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-local}

  frontend:
    build:
      context: ../..
      dockerfile: infrastructure/docker/frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
